name: freezed_annotation
description: >
  Annotations for the freezed code-generator.
  This package does nothing without freezed too.
version: 0.13.0-nullsafety.0
homepage: https://github.com/nipun-solutelabs/freezed
# authors:
#   - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.10.0-0.0.dev <3.0.0"

dependencies:
  collection:
  json_annotation:
  meta: 
